name: Deploy .NET Application to Azure Windows Server VM

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'  # Specify the .NET version you are using

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish --configuration Release --no-build --output ./output

      - name: Compress output
        run: Compress-Archive -Path ./output/* -DestinationPath ./app.zip

      - name: Copy artifact to VM via SCP
        uses: appleboy/scp-action@master
        with:
          source: ./app.zip
          target: ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/C:/Users/abhi_deployments/
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy application on VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /C:/Users/abhi_deployments/
            Expand-Archive -Path app.zip -DestinationPath ./app -Force
            Remove-Item -Path app.zip
            # Replace the following with your application's specific deployment steps
            # Example: Copy files to IIS directory
            Copy-Item -Path ./app/* -Destination "C:\inetpub\wwwroot" -Recurse -Force
            # Restart IIS to apply changes
            iisreset
