name: Deploy .NET Application to Azure Windows Server VM

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'  # Specify the .NET version you are using

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish --configuration Release --no-build --output ./output

      - name: Compress output
        run: |
          Compress-Archive -Path ./output/* -DestinationPath ./app.zip

      - name: Deploy to Azure Windows Server VM
        run: |
          $ErrorActionPreference = "Stop"
          $username = "${{ secrets.AZURE_VM_USERNAME }}"
          $password = "${{ secrets.AZURE_VM_PASSWORD }}"
          $securePassword = ConvertTo-SecureString $password -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential ($username, $securePassword)
          
          # Prepare session options
          $sessionOptions = New-PSSessionOption -SkipCACheck -SkipCNCheck -SkipRevocationCheck
          
          # Create remote session
          $session = New-PSSession -ComputerName "${{ secrets.AZURE_VM_IP }}" -Credential $credential -UseSSL -SessionOption $sessionOptions
          
          # Copy files to remote VM
          Copy-Item -Path ./app.zip -Destination "C:\inetpub\wwwroot\app.zip" -ToSession $session

          # Execute remote commands
          Invoke-Command -Session $session -ScriptBlock {
              Expand-Archive -Path "C:\inetpub\wwwroot\app.zip" -DestinationPath "C:\inetpub\wwwroot\app" -Force
              Remove-Item -Path "C:\inetpub\wwwroot\app.zip"
              # Restart IIS to apply changes
              iisreset
          }
          
          # Remove session
          Remove-PSSession -Session $session
