name: Build and Deploy to Windows VM

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest  # Use a Linux runner for the GitHub Actions workflow

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'  # Adjust to your .NET version

    - name: Build application
      run: |
        dotnet build -c Release
        dotnet publish -c Release -o ./publish

    - name: Create ZIP file
      run: |
        cd ./publish
        zip -r ../app.zip .
        cd ..

    - name: Upload artifact to VM via SCP
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        scp -i private_key.pem -P 22 ./app.zip ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/C:/Users/abhi_deployments/
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy application on VM via SSH
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        ssh -i private_key.pem -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          # Ensure PowerShell script execution is enabled
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
          
          # Extract the ZIP file
          Expand-Archive -Path C:/Users/abhi_deployments/app.zip -DestinationPath C:/Users/abhi_deployments/app -Force
          
          # Remove the ZIP file
          Remove-Item -Path C:/Users/abhi_deployments/app.zip
          
          # Copy files to the IIS directory
          Copy-Item -Path C:/Users/abhi_deployments/app/* -Destination C:/inetpub/wwwroot -Recurse -Force
        EOF
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
